title: <p align="center"> David Issá </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/david-issá">LinkedIn</a> |
  <a href="https://github.com/davidissa99">GitHub</a>
  </p>
  
  <p align="justify">
  I am a 24 year old data enthusiastic. Did my MS degree in Economics in Nova School of Business and Economics, and currently I am finishing a postgraduate study in Data Science in Nova Information Management School.
  <br><br>
  I am a Consultant in Management Solutions, currently doing a project for a G-SIB, providing support to the Enterprise and Risk Management department.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
