title: <p align="center"> David Issá </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/david-issá">LinkedIn</a> |
  <a href="https://github.com/davidissa99">GitHub</a>
  </p>
  
  <p align="justify">
  Hello, I'm David, a dedicated Data Analyst Consultant with a passion for leveraging data-driven insights to solve complex business challenges. 
  With a strong background in economics and a postgraduate degree in Data Science, I bring a unique blend of analytical expertise and domain knowledge to the table.
  
  <br><br>
  In my current role, I've collaborated on high-impact projects within a Global Bank's. Notable achievements include developing an innovative information management tool to 
  streamline data accessibility and automate risk analysis processes. By creating intuitive dashboards and utilizing advanced statistical techniques, 
  I've empowered decision-makers to navigate monthly closings with confidence and clarity.

  <br><br>
  I'm driven by a desire to uncover meaningful patterns in data and translate them into actionable insights that drive strategic decision-making. 
  I thrive on the challenge of extracting value from complex datasets and delivering tangible results that make a difference.

  <br><br>
  Core Competences and Tech Stack:
  • Python • R • SQL • Power BI • Tableau • Big Data • Data Wrangling • Statistical Analysis • Machine Learning • Supervised learning • Unsupervised learning 
  • Data Visualization • Business Intelligence • Data Mining • Database Management • AWS • NoSQL • Spark • Hadoop
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
