title: <p align="center"> David Issá </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/david-issá">LinkedIn</a> |
  <a href="https://github.com/davidissa99">GitHub</a>
  </p>
  
  <p align="justify">
  I am a dedicated Data Scientist with a passion for leveraging data-driven insights to solve complex business challenges. With a strong background in Economics and Data Science, I bring a unique blend of analytical expertise and domain knowledge to the table.

  <br><br>
  I'm driven by a desire to translate any type of data into actionable insights, thriving on the challenge of extracting value from complex datasets and delivering tangible and useful results.

  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
